name: FSL - DevOps Challenge
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./rdicidr-0.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [12.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: apt update and upgrade
      run: sudo apt-get update && sudo apt-get upgrade

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run lint
    - run: |
        npm install prettier
        npm run prettier
    - run: CI=true npm run test
    - run: npm run build

    